services:
  # ELibrary Application
  elibrary:
    container_name: elibrary
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;https://+:5001
      - ASPNETCORE_HTTPS_PORTS:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=100203
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificates/aspnetapp.pfx
      - REDIS_URL=127.0.0.1:6379
    build:
      context: .
      dockerfile: FPTU_ELibrary.API/Dockerfile
    ports:
      - 5000:80
      - 5001:5001
    volumes:
      - ./FPTU_ELibrary.API/aspnetapp.pfx:/app/certificates/aspnetapp.pfx:ro
    networks:
      - app-net
    depends_on:
      - sqlserver
      - elasticsearch
  # SQL Server
  sqlserver:
      container_name: sqlserver
      image: mcr.microsoft.com/mssql/server:2022-latest
      environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=@ELibrary123
      ports:
        - 1433:1433
      volumes:
        - sqlserver-data:/var/opt/mssql
      networks:
        - app-net
  # ElasticSearch
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.0
    environment:
     - xpack.security.enabled=false
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms1g -Xmx1g"  # Limit heap size to 1GB
     - bootstrap.memory_lock=true  # Prevent Elasticsearch from being swapped
    ports:
     - 9200:9200
    volumes:
     - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
     - app-net 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
        resources:
           limits:
               memory: 2g  # Limit container memory to 2GB
           reservations:
               memory: 1g  # Reserve 1GB of memory
  # Kibana
  kibana:
     container_name: kibana
     image: kibana:7.17.0
     environment:
         - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
     depends_on:
         - elasticsearch
     ports:
         - 5601:5601   
     networks:
         - app-net
volumes:
  elasticsearch-data:
  sqlserver-data:
networks:
  app-net:
    driver: bridge
