name: Build and deploy ASP.Net Core app to Azure Web App - SEP-ELibrary-WOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write           # required for OIDC login
  contents: read            # required for checkout & artifacts

jobs:
  build:
    runs-on: windows-latest
    permissions: contents:read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'    # .NET 8 LTS

      - name: Restore dependencies
        run: dotnet restore FPTU_ELibrary.API/FPTU_ELibrary.API.csproj

      - name: Build project
        run: dotnet build FPTU_ELibrary.API/FPTU_ELibrary.API.csproj --configuration Release --no-restore

      - name: Publish to folder
        run: dotnet publish FPTU_ELibrary.API/FPTU_ELibrary.API.csproj --configuration Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./app

      - name: Azure login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1375FD11475649E2984EFA111628C003 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C6C417F674484AA5AA29662470ECFF95 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0476099C34B045ECA32A31697842FDCF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: SEP-ELibrary-WOS
          slot-name: Production
          package: ./app
